CREATE TABLE [dbo].[Holdings-202104091614486_LACEYA SUSANNA RIEKERT_JSE] (
    [_Name_]                NVARCHAR (50) NOT NULL,
    [_Code_]                NVARCHAR (50) NOT NULL,
    [_Description_]         NVARCHAR (50) NOT NULL,
    [_Investment_Category_] NVARCHAR (50) NOT NULL,
    [_Asset_Type_]          NVARCHAR (50) NOT NULL,
    [_Sector_]              NVARCHAR (50) NOT NULL,
    [_Quantity_]            NVARCHAR (50) NOT NULL,
    [_Pending_Qty_]         NVARCHAR (50) NOT NULL,
    [_Demat_Qty_]           NVARCHAR (50) NOT NULL,
    [_Reference_Currency_]  NVARCHAR (50) NOT NULL,
    [_Reference_Unit_Cost_] NVARCHAR (50) NOT NULL,
    [_Reference_Cost_]      NVARCHAR (50) NOT NULL,
    [_Reference_Price_]     NVARCHAR (50) NOT NULL,
    [_Reference_Value_]     NVARCHAR (50) NOT NULL,
    [_Base_Currency_]       NVARCHAR (50) NOT NULL,
    [_Base_Unit_Cost_]      NVARCHAR (50) NOT NULL,
    [_Base_Cost_]           NVARCHAR (50) NOT NULL,
    [_Base_Price_]          NVARCHAR (50) NOT NULL,
    [_Base_Value_]          NVARCHAR (50) NOT NULL,
    [_Exchange_Rate_]       NVARCHAR (50) NOT NULL,
    [_Profit_Loss_]         NVARCHAR (50) NOT NULL,
    [_Move___]              NVARCHAR (50) NOT NULL,
    [_Daily_Profit_Loss_]   NVARCHAR (50) NOT NULL,
    [_Daily_Move___]        NVARCHAR (50) NOT NULL,
    [_Asset_Class___]       NVARCHAR (50) NOT NULL,
    [_Portfolio___]         NVARCHAR (50) NOT NULL,
    [_Yield___]             NVARCHAR (50) NOT NULL,
    [_Annual_Income_]       NVARCHAR (50) NOT NULL,
    [_Initial_Margin_]      NVARCHAR (50) NOT NULL,
    [_ISL_Margin_]          NVARCHAR (50) NOT NULL
);

