CREATE TABLE [Finance].[InvestmentTransactionsProcessed] (
    [1614486_Laceya Susanna Riekert_JSE] NVARCHAR (255) NULL,
    [F2]                                 NVARCHAR (255) NULL,
    [F3]                                 NVARCHAR (255) NULL,
    [F4]                                 NVARCHAR (255) NULL,
    [F5]                                 NVARCHAR (255) NULL,
    [F6]                                 NVARCHAR (255) NULL,
    [F7]                                 NVARCHAR (255) NULL,
    [F8]                                 NVARCHAR (255) NULL,
    [F9]                                 NVARCHAR (255) NULL,
    [F10]                                NVARCHAR (255) NULL,
    [F11]                                NVARCHAR (255) NULL,
    [F12]                                NVARCHAR (255) NULL,
    [F13]                                NVARCHAR (255) NULL,
    [F14]                                NVARCHAR (255) NULL,
    [F15]                                NVARCHAR (255) NULL,
    [F16]                                NVARCHAR (255) NULL,
    [F17]                                NVARCHAR (255) NULL,
    [F18]                                NVARCHAR (255) NULL,
    [F19]                                NVARCHAR (255) NULL,
    [F20]                                NVARCHAR (255) NULL,
    [F21]                                NVARCHAR (255) NULL,
    [F22]                                NVARCHAR (255) NULL,
    [F23]                                NVARCHAR (255) NULL,
    [F24]                                NVARCHAR (255) NULL,
    [F25]                                NVARCHAR (255) NULL,
    [F26]                                NVARCHAR (255) NULL
);

